; FILE: platformio.ini
; PROJECT: AutoGerminator v2.0
[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino

monitor_speed   = 115200
monitor_filters = send_on_enter

build_flags =
    -std=gnu++14

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0

lib_extra_dirs =
    lib/Sensors
    lib/Actors
    lib/ProfileManager
    lib/Network
    